// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAMGokywy8GnPKiouxQLEI9yLF_xk_DHjU',
    appId: '1:909456218271:web:a6e4005e964c9437d72aaa',
    messagingSenderId: '909456218271',
    projectId: 'loginbackend-d7750',
    authDomain: 'loginbackend-d7750.firebaseapp.com',
    storageBucket: 'loginbackend-d7750.firebasestorage.app',
    measurementId: 'G-TJNKY6XYT1',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBsaJFjEReoTepnjfC6h4sUuU7RXTWuL4U',
    appId: '1:909456218271:android:2fc63bf3a37f95fad72aaa',
    messagingSenderId: '909456218271',
    projectId: 'loginbackend-d7750',
    storageBucket: 'loginbackend-d7750.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBLCsIckYiQoixsT7qsYvGazvoBNKXwMt4',
    appId: '1:909456218271:ios:305f784e343c7f47d72aaa',
    messagingSenderId: '909456218271',
    projectId: 'loginbackend-d7750',
    storageBucket: 'loginbackend-d7750.firebasestorage.app',
    iosBundleId: 'com.example.welcome',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBLCsIckYiQoixsT7qsYvGazvoBNKXwMt4',
    appId: '1:909456218271:ios:305f784e343c7f47d72aaa',
    messagingSenderId: '909456218271',
    projectId: 'loginbackend-d7750',
    storageBucket: 'loginbackend-d7750.firebasestorage.app',
    iosBundleId: 'com.example.welcome',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAMGokywy8GnPKiouxQLEI9yLF_xk_DHjU',
    appId: '1:909456218271:web:0a5d211a0c8a967cd72aaa',
    messagingSenderId: '909456218271',
    projectId: 'loginbackend-d7750',
    authDomain: 'loginbackend-d7750.firebaseapp.com',
    storageBucket: 'loginbackend-d7750.firebasestorage.app',
    measurementId: 'G-G8DMVK3B55',
  );
}
